### ISSUE TITLE
Browser Freezes

### ISSUE THREAD

**Issue by bryanwillis** [darcyclarke/Watch.js#6]
Hey when I click Animate Box on the example page, it's causing the entire page to freeze (no scrolling, closing tab, etc). If I catch it quick enough I can close the tab, but if I don't do it within like 10 seconds my cpu skyrockets (with chrome) and I have to force quit. At first I thought there was something wrong with chrome, but it only happens on the example site, and I checked with chrome, safari, and firefox. I have two mackbook pro's and they are both running mavericks. Anyway, thought I'd let you know so you know to check with mavericks if you know anyone who has one (hopefully this isn't something wrong with my computers!)

**Comment by wmassingham** [comment]
Still present on all demo pages. Locks up Chrome 43, Firefox 38, and IE 8.
